Css canvas medical
Jc-Leon/c0621-code-solutions pull request #27
Opened 2021-06-30 15:51 UTC by Jc-Leon

<img width="1440" alt="Screen Shot 2021-06-30 at 8 48 23 AM" src="https://user-images.githubusercontent.com/84432043/123992213-46b15480-d980-11eb-8f86-c158de733fa8.png">
<img width="1440" alt="Screen Shot 2021-06-30 at 8 48 43 AM" src="https://user-images.githubusercontent.com/84432043/123992225-4a44db80-d980-11eb-98f0-705881d7859d.png">
<img width="1440" alt="Screen Shot 2021-06-30 at 8 48 54 AM" src="https://user-images.githubusercontent.com/84432043/123992228-4add7200-d980-11eb-984d-9e95160be896.png">

2021-07-02 00:33 UTC, codingcodymiller requested changes
Hey dude!! The position of your text over the hero image is not matching the position on the example, please revise

2021-07-07 17:44 UTC, codingcodymiller requested changes
Hey Jc! I see you are using text for the logo rather than the images provided, please switch those over to being the logo images provided in the images folder. Make sure you attach updated screenshots after making the change! 😁

2021-07-09 05:46 UTC, Jc-Leon commented
<img width="213" alt="Screen Shot 2021-07-08 at 10 44 45 PM" src="https://user-images.githubusercontent.com/84432043/125029368-60b4fc00-e03e-11eb-9e85-4efa2a5bdf8a.png">
<img width="416" alt="Screen Shot 2021-07-08 at 10 44 41 PM" src="https://user-images.githubusercontent.com/84432043/125029373-614d9280-e03e-11eb-80a9-d1b6741b76d7.png">

2021-07-09 18:02 UTC, codingcodymiller requested changes
Hey dude! Can I see updated screenshots for your entire output after the changes I've requested? I want to see the image portion too, and re-check if the rest matches the example.

2021-07-09 20:20 UTC, Jc-Leon commented
<img width="1143" alt="Screen Shot 2021-07-09 at 1 19 59 PM" src="https://user-images.githubusercontent.com/84432043/125131949-7961f800-e0b8-11eb-9bff-b57c581ccf2e.png">
<img width="1157" alt="Screen Shot 2021-07-09 at 1 20 05 PM" src="https://user-images.githubusercontent.com/84432043/125131955-7bc45200-e0b8-11eb-94a0-4d8833086a1a.png">
<img width="1160" alt="Screen Shot 2021-07-09 at 1 19 22 PM" src="https://user-images.githubusercontent.com/84432043/125131959-7cf57f00-e0b8-11eb-8f64-d0b2d97f5b54.png">

2021-07-12 17:38 UTC, codingcodymiller requested changes
Hey dude! I gave you a couple notes, but I have a couple more broad notes for you:
1. All of your sizing in this is on an element-by-element individual basis, there is no use of layout classes at all, please revise this to make use of layout classes so your styling can be more succinct
2. There is a lot of repetition of styling throughout your stylesheet, try to find instances of styling that is heavily repeated and create a class for that specific styling that you can apply to any elements that need that styling. That way, you can get the same effect with a much more trim stylesheet

2021-07-12 17:38 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +    font-size: 35px;p
typo

2021-07-12 17:38 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +  bottom: -21rem;
You _definitely_ don't want to use negative values for things like this. What is the purpose of this? Did you make the parent element of this `relative` so you can confine this element to its containing block?

2021-08-23 20:00 UTC, merged