Javascript functions practice
Jc-Leon/c0621-code-solutions pull request #34
Opened 2021-07-06 02:55 UTC by Jc-Leon

2021-07-06 17:12 UTC, codingcodymiller requested changes
Hey Jc, nice start here! Some notes for you:

Also, please include a screenshot with all your tests passing

2021-07-06 17:12 UTC, codingcodymiller commented on javascript-functions-practice/get-element-at-index.js
> +  }
This should not require a loop

2021-07-06 17:12 UTC, codingcodymiller commented on javascript-functions-practice/get-last-character.js
> +  }
This should not require a loop. Strings have indexes just like arrays, how can you access the value at the last index of an array or string?

2021-07-06 18:13 UTC, Jc-Leon commented
<img width="457" alt="Screen Shot 2021-07-06 at 11 12 46 AM" src="https://user-images.githubusercontent.com/84432043/124647685-27686a80-de4b-11eb-9934-b9287788225c.png">
<img width="571" alt="Screen Shot 2021-07-06 at 11 12 14 AM" src="https://user-images.githubusercontent.com/84432043/124647693-29322e00-de4b-11eb-8945-5fb762f4ca39.png">
<img width="591" alt="Screen Shot 2021-07-06 at 11 12 26 AM" src="https://user-images.githubusercontent.com/84432043/124647696-2a635b00-de4b-11eb-8448-52c2892a5144.png">
<img width="556" alt="Screen Shot 2021-07-06 at 11 12 37 AM" src="https://user-images.githubusercontent.com/84432043/124647699-2afbf180-de4b-11eb-8e67-1059cb04223d.png">

2021-07-12 17:30 UTC, codingcodymiller requested changes

2021-07-12 17:30 UTC, codingcodymiller commented on javascript-functions-practice/get-last-character.js
> +  return string.length = string[string.length-1]
This should just be `return string[string.length - 1]`

2021-08-04 21:33 UTC, codingcodymiller approved these changes

2021-08-04 21:34 UTC, merged