completed dom-querying
Jc-Leon/c0621-code-solutions pull request #35
Opened 2021-07-06 18:10 UTC by Jc-Leon

<img width="275" alt="Screen Shot 2021-07-06 at 11 05 16 AM" src="https://user-images.githubusercontent.com/84432043/124647362-b628b780-de4a-11eb-9195-52689a01c7a1.png">

2021-07-06 22:55 UTC, codingcodymiller requested changes

2021-07-06 22:55 UTC, codingcodymiller commented on dom-querying/main.js
> +document.querySelector("h1")
This line isn't necessary, you aren't saving the return anywhere.

2021-07-06 22:55 UTC, codingcodymiller commented on dom-querying/main.js
> +document.querySelector("#explanation")
This line isn't necessary, you aren't saving the return anywhere.

2021-07-06 22:55 UTC, codingcodymiller commented on dom-querying/main.js
> +document.querySelector(".hint")
This line isn't necessary, you aren't saving the return anywhere.

2021-07-06 22:55 UTC, codingcodymiller commented on dom-querying/main.js
> +document.querySelectorAll("p")
This line isn't necessary, you aren't saving the return anywhere.

2021-07-06 22:55 UTC, codingcodymiller commented on dom-querying/main.js
> +document.querySelectorAll(".example-link")
This line isn't necessary, you aren't saving the return anywhere.

2021-07-07 08:47 UTC, Jc-Leon commented on dom-querying/main.js
> +document.querySelectorAll(".example-link")
whoops sorry about that i think overlooked at what the instructions were stating 😓 thank you for clarifying it more

2021-07-07 17:25 UTC, codingcodymiller approved these changes

2021-07-10 23:42 UTC, merged