Dom manipulation
Jc-Leon/c0621-code-solutions pull request #38
Opened 2021-07-07 08:36 UTC by Jc-Leon

<img width="404" alt="Screen Shot 2021-07-07 at 1 35 55 AM" src="https://user-images.githubusercontent.com/84432043/124727579-b5803780-dec3-11eb-998e-0fe16fc05846.png">

2021-07-07 17:29 UTC, codingcodymiller requested changes
Great start!! One note for you:

2021-07-07 17:29 UTC, codingcodymiller commented on dom-manipulation/main.js
> +  }
With the way you have this set up, you are keeping all the old classes too, which you don't want to do. That is why your text is still black on your final button, I believe. You should rewrite the class list every time, to include `hot-button` in addition to the new class for the button temperature

2021-07-10 00:33 UTC, Jc-Leon commented on dom-manipulation/main.js
> +  }
<img width="260" alt="Screen Shot 2021-07-09 at 5 31 39 PM" src="https://user-images.githubusercontent.com/84432043/125146657-bf7c8300-e0db-11eb-8eba-6d9f782ae2ee.png">

2021-07-12 17:29 UTC, codingcodymiller approved these changes

2021-07-13 23:55 UTC, merged