Javascript loops practice
Jc-Leon/c0621-code-solutions pull request #41
Opened 2021-07-09 09:04 UTC by Jc-Leon

<img width="599" alt="Screen Shot 2021-07-09 at 1 52 30 AM" src="https://user-images.githubusercontent.com/84432043/125053083-86033380-e059-11eb-8566-75c1b2bc6d4d.png">
<img width="658" alt="Screen Shot 2021-07-09 at 1 52 22 AM" src="https://user-images.githubusercontent.com/84432043/125053088-87ccf700-e059-11eb-9855-4d7d6aa69524.png">
hey cody i went to after hours like you said and it actually helped me guide me in the right direction but just ran into 1 issue if you could tell me what tell me what i did wrong i'd appreciate it 🥺

2021-07-09 16:19 UTC, codingcodymiller requested changes
Hey dude! Your problem is that your function is treating `"7"` as a seven, but that's a string, so it should not be considered as the number `7`

2021-07-10 00:37 UTC, Jc-Leon commented
i understand what youre telling me but how come on the other tests it allowed them to go through but on this one it didnt or is it  something im missing?

2021-08-03 02:51 UTC, Jc-Leon commented
<img width="374" alt="Screen Shot 2021-08-02 at 7 49 55 PM" src="https://user-images.githubusercontent.com/84432043/127949986-700069dd-4889-43de-8f7f-65b136a0aa5f.png">

2021-08-04 21:35 UTC, codingcodymiller requested changes

2021-08-04 21:35 UTC, codingcodymiller commented on javascript-loops-practice/includes-seven.js
> +    if (Number.isInteger(array[i]) && array[i] <= 7) {
This is checking for numbers that are less than or equal to 7, the function is meant to check for the presence of the `number` 7 only

2021-08-24 17:53 UTC, merged